baseURL = "http://altruismeefficacequebec.org/"
theme = "local-ea-template"
DefaultContentLanguage = "fr"
googleAnalytics = "UA-115932370-1"

[params]

[Languages]

[Languages.en]
title = "Effective Altruism Québec"
weight = 2
languageCode = "en"

[Languages.en.general]
fullTitle = "Effective Altruism Québec"
strapline = "Helping you do good better"

[Languages.en.groupinfo]
legalOrgName = "Effective Altruism Québec"
orgLocations = "Québec, Canada"
contactEmail = "info@altruismeefficacequebec.org"

[Languages.en.navbar]
home = "Home"
faq = "FAQ"
effectiveAltruism = "Effective Altruism"
aboutEA = "About EA"
readingMaterial = "Reading Material"
keyTerms = "Key Terms"
organizations = "Organizations"
contact = "Contact"
getInvolved = "Get Involved"

[Languages.en.pages]
contactPageHeader = "Contact us"
aboutEAPageHeader = "What is Effective Altruism?"

[Languages.en.homepage]
topBannerText = "Who are we?"
leadText = "We're a group of people who want to help you answer the question: how can I do good better?"
firstSectionHeader = "Doing good better"
firstSectionText = "We want to help you use evidence and reason to make the world a better place."
secondSectionHeader = "Building a community"
secondSectionText = "We are a welcoming group dedicated to promoting, inspiring and supporting one another to achieve altruistic goals."
thirdSectionHeader = "Finding better ways to help"
thirdSectionText = "We are a welcoming group dedicated to promoting, inspiring and supporting one another to achieve altruistic goals."
bottomBannerText = "A proud member of the effective altruism network"

[Languages.en.contactform]
leadText = "Say hi!"
senderName = "Your name (required)"
senderEmail = "Your email (required)"
emailSubject = "Subject"
emailMessage = "Your Message"
send = "Send"

[Languages.en.jumbotron]
# These are the buttons right under the header that appears on the main page.
# You can use them to link to a mailing list or Facebook page.
# Make sure the links start with http:// or https://
firstButtonText = "Facebook page"
firstButtonLink = "https://www.facebook.com/pg/AltruismeEfficaceQuebec/"
secondButtonText = "Montréal Meetup"
secondButtonLink = "https://www.meetup.com/AltruismeEfficaceMontreal/"
thirdButtonText = "Youtube"
thirdButtonLink = "https://www.youtube.com/channel/UCtyCNnfJCS3ruTEB8kmcgSg?view_as=subscriber"
# Remove the # before the text to add the optional Meetup button
# meetupButtonText = "Find us on Meetup"

[Languages.en.urls]
# If your group does not have URLs for these, just add # before the line
# to remove the link from the site
facebookUrl = "https://www.facebook.com/pg/AltruismeEfficaceQuebec/"
twitterUrl = "https://twitter.com/ae_quebec"
meetupUrl = "https://www.meetup.com/AltruismeEfficaceMontreal/"


[Languages.fr]
languageCode = "fr"
title = "Altruisme Efficace Québec"
weight = 1

[Languages.fr.general]
fullTitle = "Altruisme Efficace Québec"
strapline = "Vous aide à faire le bien, mieux"

[Languages.fr.groupinfo]
legalOrgName = "Altruisme Efficace Québec"
orgLocations = "Québec, Canada"
contactEmail = "info@altruismeefficacequebec.org"

[Languages.fr.navbar]
home = "Accueil"
faq = "FAQ"
effectiveAltruism = "Altruisme Efficace"
aboutEA = "À propos"
readingMaterial = "Lectures"
keyTerms = "Mots clés"
organizations = "Organisations"
contact = "Contact"
getInvolved = "S'impliquer"

[Languages.fr.pages]
contactPageHeader = "Contactez nous"
aboutEAPageHeader = "C'est quoi l'Altruisme Efficace?"

[Languages.fr.homepage]
topBannerText = "Qui sommes-nous?"
leadText = "Nous sommes un groupe de gens qui veulent vous aider à répondre à la question: comment puis-je faire le bien, mieux?"
firstSectionHeader = "Faire le bien, mieux"
firstSectionText = "Nous voulons vous aider à utiliser la raison et ainsi que les faits pour rendre le monde meilleur."
secondSectionHeader = "Bâtir une communauté"
secondSectionText = "Nous sommes un groupe ouvert, dédié à s’encourager, s’inspirer et se soutenir les un-e-s les autres afin de parvenir à nos objectifs altruistes."
thirdSectionHeader = "Trouver de meilleures façons d'aider"
thirdSectionText = "Certains projets sont des milliers de fois plus efficaces que les autres. Nous appliquons logique et recherche pour maximiser notre impact."
bottomBannerText = "Groupe membre du réseau d’altruisme efficace"

[Languages.fr.contactform]
leadText = "Dites Allô!"
senderName = "Votre nom (requis)"
senderEmail = "Votre courriel (requis)"
emailSubject = "Sujet"
emailMessage = "Votre message:"
send = "Envoyer"

[Languages.fr.jumbotron]
firstButtonText = "Page Facebook"
firstButtonLink = "https://www.facebook.com/pg/AltruismeEfficaceQuebec/"
secondButtonText = "Meetup Montréal"
secondButtonLink = "https://www.meetup.com/AltruismeEfficaceMontreal/"
thirdButtonText = "Youtube"
thirdButtonLink = "https://www.youtube.com/channel/UCtyCNnfJCS3ruTEB8kmcgSg?view_as=subscriber"
#meetupButtonText = "Finden Sie uns auf Meetup"

[Languages.fr.urls]
facebookUrl = "https://www.facebook.com/pg/AltruismeEfficaceQuebec/"
twitterUrl = "https://twitter.com/ae_quebec"
meetupUrl = "https://www.meetup.com/Effective-Altruism-Montreal-Altruisme-Efficace-Montreal/"
